language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  
script:
  - cargo test -v
  - cargo build -v --release
  - target/release/zoneq --help
  - target/release/zoneq .example.com example.zone

cache: cargo
